버그
음.. 재시작하고
MissingReferenceException: The object of type 'Image' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.EventSystems.UIBehaviour.IsActive () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/UIBehaviour.cs:28)
UnityEngine.UI.Graphic.SetMaterialDirty () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Graphic.cs:313)
UnityEngine.UI.Graphic.SetAllDirty () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Graphic.cs:263)
UnityEngine.UI.Image.set_sprite (UnityEngine.Sprite value) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Image.cs:295)
Spawner.UpdateNextTetrominoImage () (at Assets/Scripts/Core/Spawner.cs:154)
Spawner.SpawnNext () (at Assets/Scripts/Core/Spawner.cs:108)
Spawner.OnGameStart () (at Assets/Scripts/Core/Spawner.cs:55)
GameManager.set_GameState (GameState value) (at Assets/Scripts/Core/GameManager.cs:43)
GameManager.OnGameReadyPanelGameStart (System.Boolean tf) (at Assets/Scripts/Core/GameManager.cs:176)
GameReadyPanel.OnStartButton () (at Assets/Scripts/UI/GameReadyPanel.cs:30)
UnityEngine.Events.InvokableCall.Invoke () (at <f7237cf7abef49bfbb552d7eb076e422>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <f7237cf7abef49bfbb552d7eb076e422>:0)
UnityEngine.UI.Button.Press () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Button.cs:70)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Button.cs:114)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:57)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:272)
UnityEngine.EventSystems.EventSystem:Update() (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:530)

이거 버그랑
Spawner 보니까 커런트 테트로미노 none이고,
Bag도 아무것도 없네. 원래 첫블록 생성되고 7개가 들어가야 되는데.
Bag가 갱신이 안되서 커런트 테트로미노도 none이고, 해당하는 이미지도 변경이 안되네

게임 레디 되는 시점에 bag이 들어가야 하는데?